name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:=
  - type: checkboxes
    attributes:
      label: Did you clear cache before opening an issue?
      description: Sometimes your browser has old files cached and the bug you are experiencing might be already fixed, or is just a side effect of a new update. If you don't know how to do that, this website should help https://www.pcmag.com/how-to/how-to-clear-your-cache-on-any-browser.
      options:
        - label: I have cleared my cache
          required: true

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched for an existing issue
          required: true

  - type: markdown
    attributes:
      value: |
        # Basic debugging
        ```
        Below fields are very important to quickly track down the issue, so please take the time to carefully check when the issue happens and when it does not.
        ```

  - type: dropdown
    attributes:
      label: Does the issue happen when logged in?
      options: ["Yes", "No", "Both"]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Issue details
        ```
        Please provide a detailed decription of whats happening, and most importantly - solid steps to reproduce the issue. This will help us find it quicker.
        ```
    validations:
      required: true