blank_issues_enabled: false
contact_links:
  - name: Feature Request or Idea
    url: https://github.com/CameronCT/nextjs-node-auth-system/discussions
    about: Use GitHub Discussions instead as it promotes more engagement.