name: Next.js Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ['self-hosted', 'linux', 'x64']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
        working-directory: ./next

      - name: Build Next App
        run: npm run build
        working-directory: ./next

      - name: Run Next App
        run: |
          pm2 startOrRestart ecosystem.config.js
        working-directory: ./next